language: node_js
node_js:
  - '0.10'
deploy:
  provider: npm
  api_key:
    secure: caiz3hBJotU644WfUyPyWZPXGPbIyGNiZnRiVNRbAWEH7mY/0ZXrntxnowFT9eduPK5doFSQUsruLgTK0bvvDRn+gRSrRtjCFgadcWmUNjGUrFTA34jiBBDDIKQu29V29qqptC7Wg6jfOkOdH4fpvrDTEe8qe8EGSGZHLJ/pnpM=
  email: jffelsinger@gmail.com
  on:
    tags: true
